#!/bin/csh
# Version: 0.1
#
# Script to run minization, equilibration and production MD 
# Modified by Luis Garreta from script generated by CHARMM-GUI 
#
# It uses dependency flag for launching production MD.
# The namd2 tool is called in another script
#

module load NAMD

set equi_prefix = step4_equilibration
set prod_prefix = step5_production
set prod_step   = step5

# Running equilibration step
#set cmm="sbatch xmd_simple_namd.sh ${equi_prefix}.inp ${equi_prefix}.out"
set cmm="sbatch xmd_simple_namdgpus.sh ${equi_prefix}.inp ${equi_prefix}.out"
echo ">>> " $cmm
set out=`eval $cmm`
set JOB=`echo $out|cut -d" " -f4`
set DEP="--dependency=afterok:$JOB"
#set DEP=""

# Running production for 1 nanoseconds
set cnt    = 1
set cntmax = 1

while ( ${cnt} <= ${cntmax} )
    # create appropriate input file using ${prod_prefix}.inp as template
    if ( ${cnt} == 1 ) then
        set outputname = "${prod_step}_${cnt}"
        # change only the output name
        sed "s/${prod_prefix}/${outputname}/" ${prod_prefix}.inp > ${outputname}_run.inp
    else
        @ cntprev = ${cnt} - 1
        set inputname  = "${prod_step}_${cntprev}"
        set outputname = "${prod_step}_${cnt}"
        # change input and output names from template file
        sed "s/${equi_prefix}/${inputname}/" ${prod_prefix}.inp | \
            sed "s/${prod_prefix}/${outputname}/" > ${outputname}_run.inp
    endif

    # run the simulation for 1 nanosecond
    #namd2 ${prod_step}_run.inp > ${outputname}.out
    set cmm="sbatch $DEP xmd_simple_namdgpus.sh ${outputname}_run.inp ${outputname}.out"
	echo ">>> " $cmm
	eval $cmm

    @ cnt += 1
end


