>Bcl-xL_human
MSQSNRELVVDFLSYkLSQKGYSWSQFsDVEENRTEAPEGTESEMEtPsAINGNPSWHLADsPAVNGATGHSSSLDAREVIPMAAVkQALREAGDEFELRYRRAFSDLTSQLHItPGTAYQSFEQVVNELFRDGVNWGRIVAFFsFGGALCVESVDKEMQVLVSRIAAWMATYLNDHLEPWIQENGGWDTFVELYGNNAAAESRKGQERFNRWFLTGMTVAGVVLLGSLFSRK

>Bcl-xL_mouse
MSQSNRELVVDFLsYKLSQKGYSWSQFSDVEENRTEAPEETEAERETPSAINGNPSWHLADsPAVNGATGHSsSLDAREVIPMAAVkQALREAGDEFELRYRRAFSDLTSQLHITPGTAYQSFEQVVNELFRDGVNWGRIVAFFSFGGALCVESVDKEMQVLVSRIASWMATYLNDHLEPWIQENGGWDTFVDLYGNNAAAESRKGQERFNRWFLTGMTVAGVVLLGSLFSRK

>Bcl-xL_rat
MSQSNRELVVDFLSYKLSQKGYSWSQFSDVEENRTEAPEETEPERETPSAINGNPSWHLADsPAVNGATGHSSSLDAREVIPMAAVKQALREAGDEFELRYRRAFsDLTSQLHITPGTAYQSFEQVVNELFRDGVNWGRIVAFFSFGGALCVESVDKEMQVLVSRIASWMATYLNDHLEPWIQENGGWDTFVDLYGNNAAAESRKGQERFNRWFLTGMTVAGVVLLGsLFSRK

