#!/bin/csh
# Generated by CHARMM-GUI (http://www.charmm-gui.org) v3.7
#
# The following shell script assumes your NAMD executable is namd2 and that
# the NAMD inputs are located in the current directory.
#
# Only one processor is used below. To parallelize NAMD, use this scheme:
#     charmrun namd2 +p4 input_file.inp > output_file.out
# where the "4" in "+p4" is replaced with the actual number of processors you
# intend to use.

set equi_prefix = step6.%d_equilibration
set prod_prefix = step7_production
set prod_step   = step7

# Running production for 10 nanoseconds
set cnt    = 11
set cntmax = 20
set JOB=9999
set DEP=""

module load NAMD

while ( ${cnt} <= ${cntmax} )
	echo "\n###################### Step $cnt ###########################"


    set cmm3="sbatch $DEP xmd_namd.sh $prod_step $cnt $prod_prefix $equi_prefix"
	echo ">>> CMM: " $cmm3
	set cmm4=`eval $cmm3`
	set JOB=`echo $cmm4|cut -d" " -f4`
	echo ">>> JOB: " $JOB
	set DEP="--dependency=afterok:$JOB"
    @ cnt += 1
end


